server:
  port: 8888

spring:
  profiles: config-server
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t


---
server:
  port: 8080

spring:
  profiles: config-client
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888